//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Maintained by hand (see KSubMaker.App.csproj): the CI agent has no Visual Studio to run the
//     ResXFileCodeGenerator single-file generator, so this file is checked in. Keep it in sync with
//     Strings.resx — one property per <data> entry, same name.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System.Globalization;
using System.Resources;

namespace KSubMaker.App.Resources;

/// <summary>
/// Strongly typed access to the neutral (Korean) string table.
///
/// Every property goes through <see cref="ResourceManager"/> rather than returning a literal, so a
/// satellite assembly built from <c>Strings.&lt;culture&gt;.resx</c> is picked up automatically once
/// <see cref="Culture"/> (or <see cref="CultureInfo.CurrentUICulture"/>) says so.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("ResXFileCodeGenerator", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCode]
public static partial class Strings
{
    private static ResourceManager? _resourceManager;

    public static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager("KSubMaker.App.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>Overrides the culture used for lookups. Null follows <see cref="CultureInfo.CurrentUICulture"/>.</summary>
    public static CultureInfo? Culture { get; set; }

    /// <summary>
    /// Returns the key itself when an entry is missing. A missing string must show up as an obviously
    /// wrong label rather than taking a window down with a <see cref="System.NullReferenceException"/>.
    /// </summary>
    private static string Get(string name) => ResourceManager.GetString(name, Culture) ?? name;

    /// <summary>KSubMaker</summary>
    public static string AppTitle => Get(nameof(AppTitle));

    /// <summary>확인</summary>
    public static string Ok => Get(nameof(Ok));

    /// <summary>취소</summary>
    public static string Cancel => Get(nameof(Cancel));

    /// <summary>저장</summary>
    public static string Save => Get(nameof(Save));

    /// <summary>닫기</summary>
    public static string Close => Get(nameof(Close));

    /// <summary>찾아보기</summary>
    public static string Browse => Get(nameof(Browse));

    /// <summary>새로 고침</summary>
    public static string Refresh => Get(nameof(Refresh));

    /// <summary>없음</summary>
    public static string NotAvailable => Get(nameof(NotAvailable));

    /// <summary>알 수 없음</summary>
    public static string Unknown => Get(nameof(Unknown));

    /// <summary>사용 가능</summary>
    public static string Available => Get(nameof(Available));

    /// <summary>사용 불가</summary>
    public static string Unavailable => Get(nameof(Unavailable));

    /// <summary>-</summary>
    public static string Dash => Get(nameof(Dash));

    /// <summary>오류</summary>
    public static string DialogTitleError => Get(nameof(DialogTitleError));

    /// <summary>경고</summary>
    public static string DialogTitleWarning => Get(nameof(DialogTitleWarning));

    /// <summary>알림</summary>
    public static string DialogTitleInfo => Get(nameof(DialogTitleInfo));

    /// <summary>확인</summary>
    public static string DialogTitleConfirm => Get(nameof(DialogTitleConfirm));

    /// <summary>KSubMaker 실행 중</summary>
    public static string SingleInstanceTitle => Get(nameof(SingleInstanceTitle));

    /// <summary>KSubMaker가 이미 실행 중입니다. 방금 창을 닫으셨다면 정리가 끝나는 중이니 잠시 뒤 다시 실행하세요.</summary>
    public static string SingleInstanceMessage => Get(nameof(SingleInstanceMessage));

    /// <summary>시작 실패</summary>
    public static string StartupFailedTitle => Get(nameof(StartupFailedTitle));

    /// <summary>프로그램을 시작하지 못했습니다. 자세한 내용은 로그 파일을 확인하세요.</summary>
    public static string StartupFailedMessage => Get(nameof(StartupFailedMessage));

    /// <summary>예기치 않은 오류</summary>
    public static string UnexpectedErrorTitle => Get(nameof(UnexpectedErrorTitle));

    /// <summary>예기치 않은 오류가 발생했습니다. 계속 사용할 수 있지만 문제가 반복되면 '로그 보기'에서 기록을 확인하세요.</summary>
    public static string UnexpectedErrorMessage => Get(nameof(UnexpectedErrorMessage));

    /// <summary>종료 처리 중 문제가 발생했습니다.</summary>
    public static string ShutdownFailedMessage => Get(nameof(ShutdownFailedMessage));

    /// <summary>KSubMaker · 한국어 자막 생성기</summary>
    public static string MainWindowTitle => Get(nameof(MainWindowTitle));

    /// <summary>대상 폴더</summary>
    public static string TargetFolderLabel => Get(nameof(TargetFolderLabel));

    /// <summary>폴더 선택</summary>
    public static string SelectFolderButton => Get(nameof(SelectFolderButton));

    /// <summary>하위 폴더 포함</summary>
    public static string IncludeSubfoldersLabel => Get(nameof(IncludeSubfoldersLabel));

    /// <summary>숨김 폴더 포함</summary>
    public static string IncludeHiddenFoldersLabel => Get(nameof(IncludeHiddenFoldersLabel));

    /// <summary>이미 한국어 자막이 있으면 건너뛰기</summary>
    public static string SkipIfKoreanSubtitleLabel => Get(nameof(SkipIfKoreanSubtitleLabel));

    /// <summary>목록 새로고침</summary>
    public static string ScanButton => Get(nameof(ScanButton));

    /// <summary>대상 폴더를 다시 검색해 새 영상은 목록에 넣고 기존 항목의 상태를 갱신합니다.</summary>
    public static string ScanHint => Get(nameof(ScanHint));

    /// <summary>검색 중단</summary>
    public static string ScanCancelButton => Get(nameof(ScanCancelButton));

    /// <summary>시작</summary>
    public static string StartButton => Get(nameof(StartButton));

    /// <summary>일시정지</summary>
    public static string PauseButton => Get(nameof(PauseButton));

    /// <summary>중단</summary>
    public static string StopButton => Get(nameof(StopButton));

    /// <summary>다시 넣기</summary>
    public static string RetryButton => Get(nameof(RetryButton));

    /// <summary>건너뛰기</summary>
    public static string CancelJobButton => Get(nameof(CancelJobButton));

    /// <summary>완료 항목 비우기</summary>
    public static string RemoveCompletedButton => Get(nameof(RemoveCompletedButton));

    /// <summary>목록에서 빼기</summary>
    public static string RemoveSelectedButton => Get(nameof(RemoveSelectedButton));

    /// <summary>결과 폴더 열기</summary>
    public static string OpenOutputFolderButton => Get(nameof(OpenOutputFolderButton));

    /// <summary>원본 위치 열기</summary>
    public static string OpenSourceFolderButton => Get(nameof(OpenSourceFolderButton));

    /// <summary>로그 보기</summary>
    public static string OpenLogButton => Get(nameof(OpenLogButton));

    /// <summary>설정</summary>
    public static string SettingsButton => Get(nameof(SettingsButton));

    /// <summary>모델 관리</summary>
    public static string ModelsButton => Get(nameof(ModelsButton));

    /// <summary>전체 선택</summary>
    public static string SelectAllButton => Get(nameof(SelectAllButton));

    /// <summary>선택 해제</summary>
    public static string ClearSelectionButton => Get(nameof(ClearSelectionButton));

    /// <summary>선택</summary>
    public static string ColumnSelected => Get(nameof(ColumnSelected));

    /// <summary>파일명</summary>
    public static string ColumnFileName => Get(nameof(ColumnFileName));

    /// <summary>길이</summary>
    public static string ColumnDuration => Get(nameof(ColumnDuration));

    /// <summary>용량</summary>
    public static string ColumnFileSize => Get(nameof(ColumnFileSize));

    /// <summary>상태</summary>
    public static string ColumnStatus => Get(nameof(ColumnStatus));

    /// <summary>전체 진행률</summary>
    public static string ColumnProgress => Get(nameof(ColumnProgress));

    /// <summary>단계 진행률</summary>
    public static string ColumnStageProgress => Get(nameof(ColumnStageProgress));

    /// <summary>남은 시간</summary>
    public static string ColumnRemaining => Get(nameof(ColumnRemaining));

    /// <summary>처리 속도</summary>
    public static string ColumnSpeed => Get(nameof(ColumnSpeed));

    /// <summary>감지 언어</summary>
    public static string ColumnDetectedLanguage => Get(nameof(ColumnDetectedLanguage));

    /// <summary>모델</summary>
    public static string ColumnModel => Get(nameof(ColumnModel));

    /// <summary>오류</summary>
    public static string ColumnError => Get(nameof(ColumnError));

    /// <summary>메모</summary>
    public static string ColumnNote => Get(nameof(ColumnNote));

    /// <summary>이 파일만 실행</summary>
    public static string RunThisMenuItem => Get(nameof(RunThisMenuItem));

    /// <summary>재생</summary>
    public static string PlayMenuItem => Get(nameof(PlayMenuItem));

    /// <summary>이름 바꾸기…</summary>
    public static string RenameMenuItem => Get(nameof(RenameMenuItem));

    /// <summary>삭제…</summary>
    public static string DeleteMenuItem => Get(nameof(DeleteMenuItem));

    /// <summary>속성</summary>
    public static string PropertiesMenuItem => Get(nameof(PropertiesMenuItem));

    /// <summary>메모…</summary>
    public static string NoteMenuItem => Get(nameof(NoteMenuItem));

    /// <summary>메모</summary>
    public static string NoteDialogTitle => Get(nameof(NoteDialogTitle));

    /// <summary>{0} 에 대한 메모</summary>
    public static string NoteDialogMessageFormat => Get(nameof(NoteDialogMessageFormat));

    /// <summary>메모를 저장했습니다.</summary>
    public static string NoteSavedMessage => Get(nameof(NoteSavedMessage));

    /// <summary>메모를 지웠습니다.</summary>
    public static string NoteClearedMessage => Get(nameof(NoteClearedMessage));

    /// <summary>처리 중인 작업의 파일은 이름을 바꾸거나 삭제할 수 없습니다.</summary>
    public static string FileActionJobRunning => Get(nameof(FileActionJobRunning));

    /// <summary>이름 바꾸기</summary>
    public static string RenameDialogTitle => Get(nameof(RenameDialogTitle));

    /// <summary>새 파일 이름을 입력하세요 (현재: {0})</summary>
    public static string RenameDialogMessageFormat => Get(nameof(RenameDialogMessageFormat));

    /// <summary>옆에 있는 자막 파일 {0}개도 같은 이름으로 바꿀까요?</summary>
    public static string RenameSidecarConfirmFormat => Get(nameof(RenameSidecarConfirmFormat));

    /// <summary>파일 이름을 바꾸지 못했습니다. 이름이 잘못됐거나 같은 이름의 항목이 이미 있습니다.</summary>
    public static string RenameFailedMessage => Get(nameof(RenameFailedMessage));

    /// <summary>파일 이름을 바꿨습니다.</summary>
    public static string RenameDoneMessage => Get(nameof(RenameDoneMessage));

    /// <summary>파일과 자막 {0}개의 이름을 바꿨습니다.</summary>
    public static string RenameDoneWithSidecarsFormat => Get(nameof(RenameDoneWithSidecarsFormat));

    /// <summary>삭제</summary>
    public static string DeleteDialogTitle => Get(nameof(DeleteDialogTitle));

    /// <summary>{0} 을(를) 휴지통으로 보낼까요?</summary>
    public static string DeleteConfirmFormat => Get(nameof(DeleteConfirmFormat));

    /// <summary>옆에 있는 자막 파일 {0}개도 함께 휴지통으로 보낼까요?</summary>
    public static string DeleteSidecarConfirmFormat => Get(nameof(DeleteSidecarConfirmFormat));

    /// <summary>휴지통으로 보내지 못했습니다.</summary>
    public static string DeleteFailedMessage => Get(nameof(DeleteFailedMessage));

    /// <summary>{0}개 항목을 휴지통으로 보냈습니다.</summary>
    public static string DeleteDoneFormat => Get(nameof(DeleteDoneFormat));

    /// <summary>결과 자막 이동</summary>
    public static string RelocateOutputsDialogTitle => Get(nameof(RelocateOutputsDialogTitle));

    /// <summary>출력 폴더 설정이 바뀌었습니다. 이미 만들어진 자막 {0}개를 새 위치로 옮길까요?</summary>
    public static string RelocateOutputsConfirmFormat => Get(nameof(RelocateOutputsConfirmFormat));

    /// <summary>자막 {0}/{1}개를 새 폴더로 옮겼습니다.</summary>
    public static string RelocateOutputsDoneFormat => Get(nameof(RelocateOutputsDoneFormat));

    /// <summary>경로</summary>
    public static string JobTooltipPathLabel => Get(nameof(JobTooltipPathLabel));

    /// <summary>상태</summary>
    public static string JobTooltipStatusLabel => Get(nameof(JobTooltipStatusLabel));

    /// <summary>큐 상태</summary>
    public static string QueueStateLabel => Get(nameof(QueueStateLabel));

    /// <summary>전체</summary>
    public static string CountTotalLabel => Get(nameof(CountTotalLabel));

    /// <summary>대기</summary>
    public static string CountPendingLabel => Get(nameof(CountPendingLabel));

    /// <summary>진행</summary>
    public static string CountRunningLabel => Get(nameof(CountRunningLabel));

    /// <summary>완료</summary>
    public static string CountCompletedLabel => Get(nameof(CountCompletedLabel));

    /// <summary>실패</summary>
    public static string CountFailedLabel => Get(nameof(CountFailedLabel));

    /// <summary>GPU</summary>
    public static string GpuLabel => Get(nameof(GpuLabel));

    /// <summary>대기 중</summary>
    public static string QueueStateIdle => Get(nameof(QueueStateIdle));

    /// <summary>실행 중</summary>
    public static string QueueStateRunning => Get(nameof(QueueStateRunning));

    /// <summary>일시정지 준비 중</summary>
    public static string QueueStatePausing => Get(nameof(QueueStatePausing));

    /// <summary>일시정지됨</summary>
    public static string QueueStatePaused => Get(nameof(QueueStatePaused));

    /// <summary>중단하는 중</summary>
    public static string QueueStateStopping => Get(nameof(QueueStateStopping));

    /// <summary>대기</summary>
    public static string JobStatusPending => Get(nameof(JobStatusPending));

    /// <summary>정보 확인</summary>
    public static string JobStatusProbing => Get(nameof(JobStatusProbing));

    /// <summary>음성 추출</summary>
    public static string JobStatusExtractingAudio => Get(nameof(JobStatusExtractingAudio));

    /// <summary>음성 인식</summary>
    public static string JobStatusTranscribing => Get(nameof(JobStatusTranscribing));

    /// <summary>번역</summary>
    public static string JobStatusTranslating => Get(nameof(JobStatusTranslating));

    /// <summary>자막 저장</summary>
    public static string JobStatusWritingSubtitle => Get(nameof(JobStatusWritingSubtitle));

    /// <summary>완료</summary>
    public static string JobStatusCompleted => Get(nameof(JobStatusCompleted));

    /// <summary>실패</summary>
    public static string JobStatusFailed => Get(nameof(JobStatusFailed));

    /// <summary>취소됨</summary>
    public static string JobStatusCancelled => Get(nameof(JobStatusCancelled));

    /// <summary>건너뜀</summary>
    public static string JobStatusSkipped => Get(nameof(JobStatusSkipped));

    /// <summary>일시정지</summary>
    public static string JobStatusPaused => Get(nameof(JobStatusPaused));

    /// <summary>-</summary>
    public static string JobStageNone => Get(nameof(JobStageNone));

    /// <summary>파일 정보 확인</summary>
    public static string JobStageProbing => Get(nameof(JobStageProbing));

    /// <summary>음성 추출</summary>
    public static string JobStageExtractingAudio => Get(nameof(JobStageExtractingAudio));

    /// <summary>음성 인식</summary>
    public static string JobStageTranscribing => Get(nameof(JobStageTranscribing));

    /// <summary>한국어 번역</summary>
    public static string JobStageTranslating => Get(nameof(JobStageTranslating));

    /// <summary>자막 파일 저장</summary>
    public static string JobStageWritingSubtitle => Get(nameof(JobStageWritingSubtitle));

    /// <summary>완료</summary>
    public static string JobStageDone => Get(nameof(JobStageDone));

    /// <summary>준비되었습니다.</summary>
    public static string ReadyMessage => Get(nameof(ReadyMessage));

    /// <summary>먼저 대상 폴더를 선택하세요.</summary>
    public static string ScanFolderNotSelected => Get(nameof(ScanFolderNotSelected));

    /// <summary>선택한 폴더가 존재하지 않습니다.</summary>
    public static string ScanFolderMissing => Get(nameof(ScanFolderMissing));

    /// <summary>폴더를 검색하는 중입니다... ({0})</summary>
    public static string ScanningFolderFormat => Get(nameof(ScanningFolderFormat));

    /// <summary>영상 {0}개를 찾았습니다. (폴더 {1}개 · {2:0.0}초)</summary>
    public static string ScanCompletedFormat => Get(nameof(ScanCompletedFormat));

    /// <summary>선택한 폴더에서 영상 파일을 찾지 못했습니다.</summary>
    public static string ScanNoFilesFound => Get(nameof(ScanNoFilesFound));

    /// <summary>검색을 취소했습니다.</summary>
    public static string ScanCancelledMessage => Get(nameof(ScanCancelledMessage));

    /// <summary>폴더 검색에 실패했습니다. ({0})</summary>
    public static string ScanFailedFormat => Get(nameof(ScanFailedFormat));

    /// <summary>파일 정보를 확인하는 중입니다... ({0}/{1})</summary>
    public static string ProbingFilesFormat => Get(nameof(ProbingFilesFormat));

    /// <summary>작업 추가 결과</summary>
    public static string EnqueueSummaryTitle => Get(nameof(EnqueueSummaryTitle));

    /// <summary>새로 추가 {0}건 · 다시 넣음 {1}건 · 이미 완료 {2}건 · 변경 없음 {3}건 · 건너뜀 {4}건</summary>
    public static string EnqueueSummaryFormat => Get(nameof(EnqueueSummaryFormat));

    /// <summary>작업이 실행 중일 때는 파일을 검색할 수 없습니다.</summary>
    public static string QueueBusyCannotScan => Get(nameof(QueueBusyCannotScan));

    /// <summary>시작할 수 있는 작업이 없습니다. 완료·실패·취소·건너뛴 작업은 [다시 넣기]를 눌러 큐에 다시 넣은 뒤 시작하세요.</summary>
    public static string NoRunnableJobs => Get(nameof(NoRunnableJobs));

    /// <summary>작업을 시작했습니다.</summary>
    public static string StartedMessage => Get(nameof(StartedMessage));

    /// <summary>현재 작업을 마친 뒤 일시정지합니다.</summary>
    public static string PauseRequestedMessage => Get(nameof(PauseRequestedMessage));

    /// <summary>작업을 중단했습니다.</summary>
    public static string StopRequestedMessage => Get(nameof(StopRequestedMessage));

    /// <summary>실행 중인 작업을 중단할까요? 진행 중이던 파일은 다음에 이어서 처리할 수 있습니다.</summary>
    public static string ConfirmStopRunning => Get(nameof(ConfirmStopRunning));

    /// <summary>먼저 목록에서 항목을 선택하세요.</summary>
    public static string NoSelectionMessage => Get(nameof(NoSelectionMessage));

    /// <summary>선택한 작업은 건너뛸 수 있는 상태가 아닙니다. 이미 완료·실패·취소·건너뛴 작업은 건너뛸 수 없습니다.</summary>
    public static string SelectionNotCancellableMessage => Get(nameof(SelectionNotCancellableMessage));

    /// <summary>선택한 작업은 다시 넣을 수 있는 상태가 아닙니다. 완료·실패·취소·건너뜀·일시정지된 작업만 큐에 다시 넣을 수 있습니다.</summary>
    public static string SelectionNotRetryableMessage => Get(nameof(SelectionNotRetryableMessage));

    /// <summary>선택한 작업은 시작할 수 있는 상태가 아닙니다. 대기·일시정지된 작업만 시작할 수 있고, 완료·실패·취소·건너뛴 작업은 [다시 넣기]를 눌러 큐에 다시 넣은 뒤 시작하세요.</summary>
    public static string SelectionNotStartableMessage => Get(nameof(SelectionNotStartableMessage));

    /// <summary>선택한 작업은 지금 이 동작을 수행할 수 있는 상태가 아닙니다.</summary>
    public static string SelectionNotEligibleMessage => Get(nameof(SelectionNotEligibleMessage));

    /// <summary>{0}건을 다시 대기열에 넣었습니다.</summary>
    public static string RetryDoneFormat => Get(nameof(RetryDoneFormat));

    /// <summary>{0}건을 건너뜁니다.</summary>
    public static string CancelDoneFormat => Get(nameof(CancelDoneFormat));

    /// <summary>완료된 항목을 목록에서 제거할까요? 이미 만들어진 자막 파일은 삭제되지 않습니다.</summary>
    public static string RemoveCompletedConfirm => Get(nameof(RemoveCompletedConfirm));

    /// <summary>완료된 항목 {0}건을 목록에서 제거했습니다.</summary>
    public static string RemoveCompletedDoneFormat => Get(nameof(RemoveCompletedDoneFormat));

    /// <summary>선택 항목 제거</summary>
    public static string RemoveSelectedConfirmTitle => Get(nameof(RemoveSelectedConfirmTitle));

    /// <summary>선택한 작업 {0}건을 목록에서 제거할까요? 캐시(체크포인트, 추출된 오디오)도 함께 삭제되지만 원본 영상과 이미 만들어진 자막은 그대로 남습니다.</summary>
    public static string RemoveSelectedConfirmFormat => Get(nameof(RemoveSelectedConfirmFormat));

    /// <summary>선택한 항목 {0}건을 캐시와 함께 제거했습니다.</summary>
    public static string RemoveSelectedDoneFormat => Get(nameof(RemoveSelectedDoneFormat));

    /// <summary>{0}건을 제거했습니다. {1}건은 아직 실행 중이라 제거하지 못했습니다.</summary>
    public static string RemoveSelectedPartialFormat => Get(nameof(RemoveSelectedPartialFormat));

    /// <summary>실행 중인 작업이 제때 멈추지 않아 일부 항목을 제거하지 못했습니다. 작업이 멈춘 뒤 다시 시도하세요.</summary>
    public static string RemoveSelectedRunningSkipped => Get(nameof(RemoveSelectedRunningSkipped));

    /// <summary>아직 결과 자막 파일이 없습니다.</summary>
    public static string OutputNotReadyMessage => Get(nameof(OutputNotReadyMessage));

    /// <summary>원본 파일을 찾을 수 없습니다.</summary>
    public static string SourceNotFoundMessage => Get(nameof(SourceNotFoundMessage));

    /// <summary>폴더를 열지 못했습니다. 경로가 올바른지 확인하세요.</summary>
    public static string OpenFolderFailedMessage => Get(nameof(OpenFolderFailedMessage));

    /// <summary>하드웨어를 확인하는 중입니다...</summary>
    public static string HardwareDetectingMessage => Get(nameof(HardwareDetectingMessage));

    /// <summary>하드웨어 정보를 가져오지 못했습니다.</summary>
    public static string HardwareDetectFailedMessage => Get(nameof(HardwareDetectFailedMessage));

    /// <summary>NVIDIA GPU 없음 · CPU 모드</summary>
    public static string GpuNotDetected => Get(nameof(GpuNotDetected));

    /// <summary>{0} · VRAM {1:0.#}GB · CUDA {2}</summary>
    public static string GpuSummaryFormat => Get(nameof(GpuSummaryFormat));

    /// <summary>작업 목록을 불러오지 못했습니다. ({0})</summary>
    public static string LoadFailedFormat => Get(nameof(LoadFailedFormat));

    /// <summary>영상이 있는 폴더를 선택하세요</summary>
    public static string SelectFolderDialogTitle => Get(nameof(SelectFolderDialogTitle));

    /// <summary>설정</summary>
    public static string SettingsWindowTitle => Get(nameof(SettingsWindowTitle));

    /// <summary>음성 인식</summary>
    public static string TabRecognition => Get(nameof(TabRecognition));

    /// <summary>번역</summary>
    public static string TabTranslation => Get(nameof(TabTranslation));

    /// <summary>자막 · 출력</summary>
    public static string TabSubtitle => Get(nameof(TabSubtitle));

    /// <summary>실행</summary>
    public static string TabExecution => Get(nameof(TabExecution));

    /// <summary>경로 · 로그</summary>
    public static string TabPaths => Get(nameof(TabPaths));

    /// <summary>시스템 정보</summary>
    public static string TabSystem => Get(nameof(TabSystem));

    /// <summary>입력 언어</summary>
    public static string SourceLanguageGroup => Get(nameof(SourceLanguageGroup));

    /// <summary>자동 감지</summary>
    public static string SourceLanguageAuto => Get(nameof(SourceLanguageAuto));

    /// <summary>직접 선택</summary>
    public static string SourceLanguageManual => Get(nameof(SourceLanguageManual));

    /// <summary>Whisper 모델</summary>
    public static string WhisperModelGroup => Get(nameof(WhisperModelGroup));

    /// <summary>자동 추천 사용</summary>
    public static string WhisperModelAuto => Get(nameof(WhisperModelAuto));

    /// <summary>직접 선택</summary>
    public static string WhisperModelManual => Get(nameof(WhisperModelManual));

    /// <summary>권장 설정</summary>
    public static string RecommendationLabel => Get(nameof(RecommendationLabel));

    /// <summary>정보</summary>
    public static string AboutGroup => Get(nameof(AboutGroup));

    /// <summary>소스 저장소</summary>
    public static string AboutRepositoryLabel => Get(nameof(AboutRepositoryLabel));

    /// <summary>연산 정밀도 (compute type)</summary>
    public static string ComputeTypeLabel => Get(nameof(ComputeTypeLabel));

    /// <summary>자동 (권장값 사용)</summary>
    public static string ComputeTypeAuto => Get(nameof(ComputeTypeAuto));

    /// <summary>빔 크기 (beam size)</summary>
    public static string BeamSizeLabel => Get(nameof(BeamSizeLabel));

    /// <summary>무음 구간 제거(VAD) 사용</summary>
    public static string VadFilterLabel => Get(nameof(VadFilterLabel));

    /// <summary>단어 단위 타임스탬프 사용</summary>
    public static string WordTimestampsLabel => Get(nameof(WordTimestampsLabel));

    /// <summary>이전 문맥 참조 (긴 영상에서 자막이 반복될 수 있음)</summary>
    public static string ConditionOnPreviousTextLabel => Get(nameof(ConditionOnPreviousTextLabel));

    public static string ExistingSubtitleUseExternal => Get(nameof(ExistingSubtitleUseExternal));

    public static string ExistingSubtitleProcessAnyway => Get(nameof(ExistingSubtitleProcessAnyway));

    public static string ExistingSubtitleRuleLabel => Get(nameof(ExistingSubtitleRuleLabel));

    public static string SubtitleSourceLabel => Get(nameof(SubtitleSourceLabel));

    public static string SubtitleSourceSettingHint => Get(nameof(SubtitleSourceSettingHint));

    public static string SubtitleSourceAudioOnly => Get(nameof(SubtitleSourceAudioOnly));

    public static string SubtitleSourceExternalFile => Get(nameof(SubtitleSourceExternalFile));

    public static string SubtitleSourceEmbeddedTrack => Get(nameof(SubtitleSourceEmbeddedTrack));

    public static string SubtitleSourceAnySubtitle => Get(nameof(SubtitleSourceAnySubtitle));

    public static string SubtitleSourceAsk => Get(nameof(SubtitleSourceAsk));

    public static string DropResolvingMessage => Get(nameof(DropResolvingMessage));

    public static string DropNothingToAddFormat => Get(nameof(DropNothingToAddFormat));

    public static string DropWhileBusyMessage => Get(nameof(DropWhileBusyMessage));

    public static string InitialPromptLabel => Get(nameof(InitialPromptLabel));

    public static string InitialPromptHint => Get(nameof(InitialPromptHint));

    /// <summary>번역 엔진</summary>
    public static string TranslationEngineGroup => Get(nameof(TranslationEngineGroup));

    /// <summary>전용 번역 모델 (NLLB)</summary>
    public static string TranslationEngineDedicated => Get(nameof(TranslationEngineDedicated));

    /// <summary>로컬 LLM</summary>
    public static string TranslationEngineLlm => Get(nameof(TranslationEngineLlm));

    /// <summary>테스트용 가짜 엔진</summary>
    public static string TranslationEngineFake => Get(nameof(TranslationEngineFake));

    /// <summary>번역 모델</summary>
    public static string TranslationModelLabel => Get(nameof(TranslationModelLabel));

    /// <summary>LLM 모델</summary>
    public static string LlmModelLabel => Get(nameof(LlmModelLabel));

    /// <summary>자동 (권장 모델 사용)</summary>
    public static string ModelAutoOption => Get(nameof(ModelAutoOption));

    /// <summary>자동 (권장 로컬 LLM 사용)</summary>
    public static string LlmAutoOption => Get(nameof(LlmAutoOption));

    /// <summary>번역 스타일</summary>
    public static string TranslationStyleLabel => Get(nameof(TranslationStyleLabel));

    /// <summary>자연스러운 한국어</summary>
    public static string TranslationStyleNatural => Get(nameof(TranslationStyleNatural));

    /// <summary>직역에 가깝게</summary>
    public static string TranslationStyleLiteral => Get(nameof(TranslationStyleLiteral));

    /// <summary>존댓말 우선</summary>
    public static string TranslationStylePolite => Get(nameof(TranslationStylePolite));

    /// <summary>반말 유지</summary>
    public static string TranslationStyleCasual => Get(nameof(TranslationStyleCasual));

    /// <summary>원문 말투 유지</summary>
    public static string TranslationStylePreserve => Get(nameof(TranslationStylePreserve));

    /// <summary>번역 배치 크기</summary>
    public static string BatchGroup => Get(nameof(BatchGroup));

    /// <summary>배치당 최대 자막 수</summary>
    public static string BatchMaxItemsLabel => Get(nameof(BatchMaxItemsLabel));

    /// <summary>배치당 최대 글자 수</summary>
    public static string BatchMaxCharsLabel => Get(nameof(BatchMaxCharsLabel));

    /// <summary>배치당 최대 길이 (초)</summary>
    public static string BatchMaxSecondsLabel => Get(nameof(BatchMaxSecondsLabel));

    /// <summary>문맥으로 넘길 이전 줄 수</summary>
    public static string ContextLinesLabel => Get(nameof(ContextLinesLabel));

    /// <summary>고유명사 사전</summary>
    public static string GlossaryGroup => Get(nameof(GlossaryGroup));

    /// <summary>등록한 원문 용어는 항상 같은 한국어로 번역됩니다. 인명·지명·작품명처럼 일관성이 중요한 낱말에 사용하세요.</summary>
    public static string GlossaryHint => Get(nameof(GlossaryHint));

    /// <summary>원문</summary>
    public static string GlossarySourceHeader => Get(nameof(GlossarySourceHeader));

    /// <summary>한국어</summary>
    public static string GlossaryTargetHeader => Get(nameof(GlossaryTargetHeader));

    /// <summary>추가</summary>
    public static string GlossaryAddButton => Get(nameof(GlossaryAddButton));

    /// <summary>삭제</summary>
    public static string GlossaryRemoveButton => Get(nameof(GlossaryRemoveButton));

    /// <summary>원문 용어를 입력하세요.</summary>
    public static string GlossarySourceRequired => Get(nameof(GlossarySourceRequired));

    /// <summary>한국어 번역을 입력하세요.</summary>
    public static string GlossaryTargetRequired => Get(nameof(GlossaryTargetRequired));

    /// <summary>이미 등록된 원문 용어입니다: {0}</summary>
    public static string GlossaryDuplicateFormat => Get(nameof(GlossaryDuplicateFormat));

    /// <summary>삭제할 항목을 먼저 선택하세요.</summary>
    public static string GlossaryNoSelection => Get(nameof(GlossaryNoSelection));

    /// <summary>자막 원본 선택</summary>
    public static string SubtitleSourceDialogTitle => Get(nameof(SubtitleSourceDialogTitle));

    /// <summary>내장 자막 트랙의 언어 표기는 없거나 틀린 경우가 많습니다. 실제 내용에 맞는 트랙을 직접 고르세요.</summary>
    public static string SubtitleSourceHint => Get(nameof(SubtitleSourceHint));

    /// <summary>자막 원본 선택…</summary>
    public static string SubtitleSourceMenuItem => Get(nameof(SubtitleSourceMenuItem));

    /// <summary>자막 원본</summary>
    public static string ColumnSubtitleSource => Get(nameof(ColumnSubtitleSource));

    /// <summary>기본(음성 인식)</summary>
    public static string SubtitleSourceDefault => Get(nameof(SubtitleSourceDefault));

    /// <summary>음성 인식 (기본 오디오 트랙)</summary>
    public static string SubtitleSourceAudioDefault => Get(nameof(SubtitleSourceAudioDefault));

    /// <summary>음성 인식 · {0}</summary>
    public static string SubtitleSourceAudioFormat => Get(nameof(SubtitleSourceAudioFormat));

    /// <summary>내장 자막 · {0}</summary>
    public static string SubtitleSourceEmbeddedFormat => Get(nameof(SubtitleSourceEmbeddedFormat));

    /// <summary>음성 #{0}</summary>
    public static string SubtitleSourceAudioShortFormat => Get(nameof(SubtitleSourceAudioShortFormat));

    /// <summary>내장 자막 #{0}</summary>
    public static string SubtitleSourceEmbeddedShortFormat => Get(nameof(SubtitleSourceEmbeddedShortFormat));

    /// <summary>{0}의 자막을 무엇으로부터 만들지 선택하세요.</summary>
    public static string SubtitleSourceMessageFormat => Get(nameof(SubtitleSourceMessageFormat));

    /// <summary>설정 화면의 기존 자막 처리 방식을 따릅니다.</summary>
    public static string SubtitleSourceUseSettingHint => Get(nameof(SubtitleSourceUseSettingHint));

    /// <summary>파일의 트랙 정보를 읽지 못했습니다.</summary>
    public static string SubtitleSourceProbeFailed => Get(nameof(SubtitleSourceProbeFailed));

    /// <summary>선택할 수 있는 오디오·자막 트랙이 없습니다.</summary>
    public static string SubtitleSourceNoTracks => Get(nameof(SubtitleSourceNoTracks));

    /// <summary>실행 중인 작업의 자막 원본은 바꿀 수 없습니다. 작업을 건너뛰거나 끝난 뒤에 다시 선택하세요.</summary>
    public static string SubtitleSourceJobRunning => Get(nameof(SubtitleSourceJobRunning));

    /// <summary>자막 원본을 변경했습니다: {0}</summary>
    public static string SubtitleSourceChangedFormat => Get(nameof(SubtitleSourceChangedFormat));

    /// <summary>기존 자막이 있는 파일</summary>
    public static string AskPerFileTitle => Get(nameof(AskPerFileTitle));

    /// <summary>{0}에는 이미 자막이 있습니다. ({1}/{2}) 이 파일의 자막 원본을 선택하세요.</summary>
    public static string AskPerFileMessageFormat => Get(nameof(AskPerFileMessageFormat));

    /// <summary>기존 자막이 있는 파일 {0}건 중 {1}건의 자막 원본을 지정했습니다.</summary>
    public static string AskPerFileDoneFormat => Get(nameof(AskPerFileDoneFormat));

    /// <summary>기존 자막 처리 방식</summary>
    public static string ExistingSubtitleGroup => Get(nameof(ExistingSubtitleGroup));

    /// <summary>항상 새로 음성 인식</summary>
    public static string ExistingSubtitleAlways => Get(nameof(ExistingSubtitleAlways));

    /// <summary>같은 이름의 자막이 있으면 건너뛰기</summary>
    public static string ExistingSubtitleSkipExternal => Get(nameof(ExistingSubtitleSkipExternal));

    /// <summary>내장 자막을 번역해서 사용</summary>
    public static string ExistingSubtitleUseEmbedded => Get(nameof(ExistingSubtitleUseEmbedded));

    /// <summary>한국어 자막이 있으면 완료로 처리</summary>
    public static string ExistingSubtitleCompleteKorean => Get(nameof(ExistingSubtitleCompleteKorean));

    /// <summary>파일마다 확인</summary>
    public static string ExistingSubtitleAsk => Get(nameof(ExistingSubtitleAsk));

    /// <summary>결과 파일 충돌 처리</summary>
    public static string OutputConflictGroup => Get(nameof(OutputConflictGroup));

    /// <summary>같은 이름의 자막 파일이 이미 있을 때</summary>
    public static string OutputConflictHint => Get(nameof(OutputConflictHint));

    /// <summary>건너뛰기</summary>
    public static string OutputConflictSkip => Get(nameof(OutputConflictSkip));

    /// <summary>덮어쓰기</summary>
    public static string OutputConflictOverwrite => Get(nameof(OutputConflictOverwrite));

    /// <summary>번호를 붙여 새 파일 만들기</summary>
    public static string OutputConflictNumbered => Get(nameof(OutputConflictNumbered));

    /// <summary>결과 파일 이름</summary>
    public static string OutputNameGroup => Get(nameof(OutputNameGroup));

    /// <summary>언어 태그</summary>
    public static string OutputSuffixLabel => Get(nameof(OutputSuffixLabel));

    /// <summary>ko → 영상이름.ko.srt · 비우면 영상이름.srt (Plex·Jellyfin은 언어 태그가 있어야 자동으로 불러옵니다)</summary>
    public static string OutputSuffixHint => Get(nameof(OutputSuffixHint));

    /// <summary>자막 서식</summary>
    public static string SubtitleFormatGroup => Get(nameof(SubtitleFormatGroup));

    /// <summary>자막 한 개의 최대 줄 수</summary>
    public static string MaxLinesPerCueLabel => Get(nameof(MaxLinesPerCueLabel));

    /// <summary>한 줄 최대 글자 수</summary>
    public static string MaxCharsPerLineLabel => Get(nameof(MaxCharsPerLineLabel));

    /// <summary>최소 표시 시간 (초)</summary>
    public static string MinCueDurationLabel => Get(nameof(MinCueDurationLabel));

    /// <summary>최대 표시 시간 (초)</summary>
    public static string MaxCueDurationLabel => Get(nameof(MaxCueDurationLabel));

    /// <summary>자막 사이 최소 간격 (ms)</summary>
    public static string MinCueGapLabel => Get(nameof(MinCueGapLabel));

    /// <summary>너무 짧은 자막 합치기</summary>
    public static string MergeShortCuesLabel => Get(nameof(MergeShortCuesLabel));

    /// <summary>작업 처리 방식</summary>
    public static string ProcessingStrategyGroup => Get(nameof(ProcessingStrategyGroup));

    /// <summary>자동 (하드웨어에 맞춰 선택)</summary>
    public static string StrategyAuto => Get(nameof(StrategyAuto));

    /// <summary>방식 A · 파일 단위 순차 처리</summary>
    public static string StrategyA => Get(nameof(StrategyA));

    /// <summary>방식 B · 전체 음성 인식 후 번역</summary>
    public static string StrategyB => Get(nameof(StrategyB));

    /// <summary>방식 C · 인식과 번역 동시 진행</summary>
    public static string StrategyC => Get(nameof(StrategyC));

    /// <summary>최대 병렬 CPU 작업 수 (0 = 자동)</summary>
    public static string MaxParallelCpuLabel => Get(nameof(MaxParallelCpuLabel));

    /// <summary>음성 미리 추출 개수 (0 = 사용 안 함)</summary>
    public static string AudioPrefetchDepthLabel => Get(nameof(AudioPrefetchDepthLabel));

    /// <summary>다음 파일의 음성을 미리 뽑아 두어 GPU가 쉬지 않게 합니다. …</summary>
    public static string AudioPrefetchDepthHint => Get(nameof(AudioPrefetchDepthHint));

    /// <summary>복구 가능한 오류는 한 번 자동으로 재시도</summary>
    public static string AutoRetryLabel => Get(nameof(AutoRetryLabel));

    /// <summary>Fake AI 모드 (모델 없이 파이프라인만 점검)</summary>
    public static string FakeAiModeLabel => Get(nameof(FakeAiModeLabel));

    /// <summary>큐 완료 후 동작</summary>
    public static string PostQueueActionGroup => Get(nameof(PostQueueActionGroup));

    /// <summary>완료 후</summary>
    public static string PostQueueActionCommandLabel => Get(nameof(PostQueueActionCommandLabel));

    /// <summary>모든 작업이 끝나면</summary>
    public static string PostQueueActionLabel => Get(nameof(PostQueueActionLabel));

    /// <summary>아무것도 하지 않음</summary>
    public static string PostQueueActionNone => Get(nameof(PostQueueActionNone));

    /// <summary>절전</summary>
    public static string PostQueueActionSleep => Get(nameof(PostQueueActionSleep));

    /// <summary>최대 절전</summary>
    public static string PostQueueActionHibernate => Get(nameof(PostQueueActionHibernate));

    /// <summary>시스템 종료</summary>
    public static string PostQueueActionShutdown => Get(nameof(PostQueueActionShutdown));

    /// <summary>실패하거나 취소된 작업이 없을 때만</summary>
    public static string PostQueueActionOnlyWhenAllSucceededLabel => Get(nameof(PostQueueActionOnlyWhenAllSucceededLabel));

    /// <summary>큐가 스스로 다 처리되어 멈췄을 때만 실행됩니다. …</summary>
    public static string PostQueueActionHint => Get(nameof(PostQueueActionHint));

    /// <summary>큐 작업 완료</summary>
    public static string PostQueueActionWindowTitle => Get(nameof(PostQueueActionWindowTitle));

    /// <summary>모든 작업이 끝났습니다. 곧 '{0}'을(를) 실행합니다.</summary>
    public static string PostQueueActionHeadingFormat => Get(nameof(PostQueueActionHeadingFormat));

    /// <summary>{0}초 후 자동 실행</summary>
    public static string PostQueueActionCountdownFormat => Get(nameof(PostQueueActionCountdownFormat));

    /// <summary>지금 실행</summary>
    public static string PostQueueActionProceedButton => Get(nameof(PostQueueActionProceedButton));

    /// <summary>취소</summary>
    public static string PostQueueActionCancelButton => Get(nameof(PostQueueActionCancelButton));

    /// <summary>큐 완료 후 동작을 취소했습니다.</summary>
    public static string PostQueueActionCancelledMessage => Get(nameof(PostQueueActionCancelledMessage));

    /// <summary>큐 완료 후 동작을 실행하지 못했습니다. 로그를 확인해 주세요.</summary>
    public static string PostQueueActionFailedMessage => Get(nameof(PostQueueActionFailedMessage));

    /// <summary>검색 기본값</summary>
    public static string ScanDefaultsGroup => Get(nameof(ScanDefaultsGroup));

    /// <summary>이미 완료된 파일도 다시 처리</summary>
    public static string ReprocessCompletedLabel => Get(nameof(ReprocessCompletedLabel));

    /// <summary>실패한 파일만 다시 처리</summary>
    public static string RetryFailedOnlyLabel => Get(nameof(RetryFailedOnlyLabel));

    /// <summary>결과 자막 위치</summary>
    public static string OutputDirectoryGroup => Get(nameof(OutputDirectoryGroup));

    /// <summary>결과 폴더</summary>
    public static string OutputDirectoryLabel => Get(nameof(OutputDirectoryLabel));

    /// <summary>비워 두면 원본 영상과 같은 폴더에 저장합니다. 지정하면 원본 폴더 구조를 그 아래에 그대로 만들어 저장합니다. 이미 자막이 만들어진 파일은 완료로 판정되어 새 위치에 다시 만들어지지 않습니다 — 옮기려면 '이미 자막이 있는 파일'을 '무시하고 다시 만들기'로 바꾸세요.</summary>
    public static string OutputDirectoryHint => Get(nameof(OutputDirectoryHint));

    /// <summary>폴더</summary>
    public static string PathsGroup => Get(nameof(PathsGroup));

    /// <summary>캐시 폴더</summary>
    public static string CacheDirectoryLabel => Get(nameof(CacheDirectoryLabel));

    /// <summary>모델 폴더</summary>
    public static string ModelDirectoryLabel => Get(nameof(ModelDirectoryLabel));

    /// <summary>로그 폴더</summary>
    public static string LogDirectoryLabel => Get(nameof(LogDirectoryLabel));

    /// <summary>비워 두면 기본 위치(%LOCALAPPDATA%\KSubMaker)를 사용합니다.</summary>
    public static string PathDefaultHint => Get(nameof(PathDefaultHint));

    /// <summary>로그</summary>
    public static string LoggingGroup => Get(nameof(LoggingGroup));

    /// <summary>로그 수준</summary>
    public static string LogLevelLabel => Get(nameof(LogLevelLabel));

    /// <summary>로그에서 파일 경로 가리기</summary>
    public static string MaskPathsLabel => Get(nameof(MaskPathsLabel));

    /// <summary>Trace (가장 상세)</summary>
    public static string LogLevelTrace => Get(nameof(LogLevelTrace));

    /// <summary>Debug (개발용)</summary>
    public static string LogLevelDebug => Get(nameof(LogLevelDebug));

    /// <summary>Information (기본)</summary>
    public static string LogLevelInformation => Get(nameof(LogLevelInformation));

    /// <summary>Warning (경고 이상)</summary>
    public static string LogLevelWarning => Get(nameof(LogLevelWarning));

    /// <summary>Error (오류만)</summary>
    public static string LogLevelError => Get(nameof(LogLevelError));

    /// <summary>Fatal (치명적 오류만)</summary>
    public static string LogLevelFatal => Get(nameof(LogLevelFatal));

    /// <summary>시스템 정보</summary>
    public static string SystemInfoGroup => Get(nameof(SystemInfoGroup));

    /// <summary>GPU 정보</summary>
    public static string GpuInfoGroup => Get(nameof(GpuInfoGroup));

    /// <summary>그래픽 카드</summary>
    public static string GpuNameLabel => Get(nameof(GpuNameLabel));

    /// <summary>VRAM</summary>
    public static string VramLabel => Get(nameof(VramLabel));

    /// <summary>CUDA</summary>
    public static string CudaLabel => Get(nameof(CudaLabel));

    /// <summary>드라이버</summary>
    public static string DriverLabel => Get(nameof(DriverLabel));

    /// <summary>CPU</summary>
    public static string CpuLabel => Get(nameof(CpuLabel));

    /// <summary>논리 코어</summary>
    public static string CoresLabel => Get(nameof(CoresLabel));

    /// <summary>메모리</summary>
    public static string RamLabel => Get(nameof(RamLabel));

    /// <summary>디스크 여유 공간</summary>
    public static string DiskLabel => Get(nameof(DiskLabel));

    /// <summary>감지 경고</summary>
    public static string DetectionWarningsLabel => Get(nameof(DetectionWarningsLabel));

    /// <summary>감지 중 경고가 없습니다.</summary>
    public static string NoDetectionWarnings => Get(nameof(NoDetectionWarnings));

    /// <summary>설정을 저장했습니다.</summary>
    public static string SettingsSavedMessage => Get(nameof(SettingsSavedMessage));

    /// <summary>설정을 저장하지 못했습니다. ({0})</summary>
    public static string SettingsSaveFailedFormat => Get(nameof(SettingsSaveFailedFormat));

    /// <summary>설정을 불러오지 못했습니다. ({0})</summary>
    public static string SettingsLoadFailedFormat => Get(nameof(SettingsLoadFailedFormat));

    /// <summary>결과 폴더 선택</summary>
    public static string SelectOutputFolderTitle => Get(nameof(SelectOutputFolderTitle));

    /// <summary>캐시 폴더 선택</summary>
    public static string SelectCacheFolderTitle => Get(nameof(SelectCacheFolderTitle));

    /// <summary>모델 폴더 선택</summary>
    public static string SelectModelFolderTitle => Get(nameof(SelectModelFolderTitle));

    /// <summary>로그 폴더 선택</summary>
    public static string SelectLogFolderTitle => Get(nameof(SelectLogFolderTitle));

    /// <summary>자동 감지</summary>
    public static string LanguageAuto => Get(nameof(LanguageAuto));

    /// <summary>영어</summary>
    public static string LanguageEn => Get(nameof(LanguageEn));

    /// <summary>일본어</summary>
    public static string LanguageJa => Get(nameof(LanguageJa));

    /// <summary>중국어</summary>
    public static string LanguageZh => Get(nameof(LanguageZh));

    /// <summary>한국어</summary>
    public static string LanguageKo => Get(nameof(LanguageKo));

    /// <summary>스페인어</summary>
    public static string LanguageEs => Get(nameof(LanguageEs));

    /// <summary>프랑스어</summary>
    public static string LanguageFr => Get(nameof(LanguageFr));

    /// <summary>독일어</summary>
    public static string LanguageDe => Get(nameof(LanguageDe));

    /// <summary>러시아어</summary>
    public static string LanguageRu => Get(nameof(LanguageRu));

    /// <summary>포르투갈어</summary>
    public static string LanguagePt => Get(nameof(LanguagePt));

    /// <summary>이탈리아어</summary>
    public static string LanguageIt => Get(nameof(LanguageIt));

    /// <summary>베트남어</summary>
    public static string LanguageVi => Get(nameof(LanguageVi));

    /// <summary>태국어</summary>
    public static string LanguageTh => Get(nameof(LanguageTh));

    /// <summary>인도네시아어</summary>
    public static string LanguageId => Get(nameof(LanguageId));

    /// <summary>힌디어</summary>
    public static string LanguageHi => Get(nameof(LanguageHi));

    /// <summary>아랍어</summary>
    public static string LanguageAr => Get(nameof(LanguageAr));

    /// <summary>튀르키예어</summary>
    public static string LanguageTr => Get(nameof(LanguageTr));

    /// <summary>네덜란드어</summary>
    public static string LanguageNl => Get(nameof(LanguageNl));

    /// <summary>폴란드어</summary>
    public static string LanguagePl => Get(nameof(LanguagePl));

    /// <summary>스웨덴어</summary>
    public static string LanguageSv => Get(nameof(LanguageSv));

    /// <summary>모델 관리</summary>
    public static string ModelsWindowTitle => Get(nameof(ModelsWindowTitle));

    /// <summary>이름</summary>
    public static string ModelColumnName => Get(nameof(ModelColumnName));

    /// <summary>종류</summary>
    public static string ModelColumnKind => Get(nameof(ModelColumnKind));

    /// <summary>상태</summary>
    public static string ModelColumnState => Get(nameof(ModelColumnState));

    /// <summary>크기</summary>
    public static string ModelColumnSize => Get(nameof(ModelColumnSize));

    /// <summary>예상 VRAM</summary>
    public static string ModelColumnVram => Get(nameof(ModelColumnVram));

    /// <summary>라이선스</summary>
    public static string ModelColumnLicense => Get(nameof(ModelColumnLicense));

    /// <summary>진행률</summary>
    public static string ModelColumnProgress => Get(nameof(ModelColumnProgress));

    /// <summary>음성 인식</summary>
    public static string ModelKindWhisper => Get(nameof(ModelKindWhisper));

    /// <summary>번역</summary>
    public static string ModelKindTranslation => Get(nameof(ModelKindTranslation));

    /// <summary>로컬 LLM</summary>
    public static string ModelKindLlm => Get(nameof(ModelKindLlm));

    /// <summary>영상 하나를 두 단계로 처리합니다 — 먼저 음성 인식 모델이 말소리를 원어 자막으로 뽑아내고, 그다음 번역 모델이 그 자막을 한국어로 다시 옮깁니다. 아래 탭에서 각 단계에 쓸 모델을 고릅니다.</summary>
    public static string ModelPipelineOverviewHint => Get(nameof(ModelPipelineOverviewHint));

    /// <summary>1차적으로 음성에서 자막을 추출하는 모델입니다. 영상 속 말소리를 원어 텍스트로 받아쓰며, 모델이 클수록 정확하지만 느립니다.</summary>
    public static string ModelKindWhisperHint => Get(nameof(ModelKindWhisperHint));

    /// <summary>전용 번역 모델(NLLB)입니다. 문장 단위로 빠르고 안정적으로 옮기지만, 앞뒤 문맥이나 말투 지시는 반영하지 못합니다.</summary>
    public static string ModelKindTranslationHint => Get(nameof(ModelKindTranslationHint));

    /// <summary>번역도 시킬 수 있는 범용 대화형 모델(LLM)입니다. 앞뒤 문맥과 말투 지시를 반영할 수 있지만, 토큰을 하나씩 만들어내는 방식이라 NLLB보다 체감상 5~20배 느립니다.</summary>
    public static string ModelKindLlmHint => Get(nameof(ModelKindLlmHint));

    /// <summary>자막을 추출한 뒤, 그것을 각 언어에 맞게 다시 번역하는 2차 과정에서 쓰는 모델입니다. 아래 NLLB(전용 번역기)와 로컬 LLM(범용 대화형 모델) 중 하나를 골라 씁니다.</summary>
    public static string ModelStepTranslationHint => Get(nameof(ModelStepTranslationHint));

    /// <summary>설치됨</summary>
    public static string ModelStateInstalled => Get(nameof(ModelStateInstalled));

    /// <summary>미설치</summary>
    public static string ModelStateNotInstalled => Get(nameof(ModelStateNotInstalled));

    /// <summary>미설치 모델은 모델 관리 화면에서 내려받은 뒤에만 사용할 수 있습니다.</summary>
    public static string SettingsModelInstallHint => Get(nameof(SettingsModelInstallHint));

    /// <summary>설치되지 않은 모델</summary>
    public static string SettingsMissingModelsTitle => Get(nameof(SettingsMissingModelsTitle));

    /// <summary>그래도 이 설정을 저장할까요?</summary>
    public static string SettingsSaveAnywayQuestion => Get(nameof(SettingsSaveAnywayQuestion));

    /// <summary>다운로드 중</summary>
    public static string ModelStateDownloading => Get(nameof(ModelStateDownloading));

    /// <summary>일시정지</summary>
    public static string ModelStatePaused => Get(nameof(ModelStatePaused));

    /// <summary>검증 중</summary>
    public static string ModelStateVerifying => Get(nameof(ModelStateVerifying));

    /// <summary>삭제 중</summary>
    public static string ModelStateDeleting => Get(nameof(ModelStateDeleting));

    /// <summary>다운로드</summary>
    public static string DownloadButton => Get(nameof(DownloadButton));

    /// <summary>일시정지</summary>
    public static string PauseDownloadButton => Get(nameof(PauseDownloadButton));

    /// <summary>재개</summary>
    public static string ResumeDownloadButton => Get(nameof(ResumeDownloadButton));

    /// <summary>삭제</summary>
    public static string DeleteModelButton => Get(nameof(DeleteModelButton));

    /// <summary>검증</summary>
    public static string VerifyModelButton => Get(nameof(VerifyModelButton));

    /// <summary>모델 폴더 열기</summary>
    public static string OpenModelFolderButton => Get(nameof(OpenModelFolderButton));

    /// <summary>먼저 모델을 선택하세요.</summary>
    public static string ModelNotSelected => Get(nameof(ModelNotSelected));

    /// <summary>권장</summary>
    public static string ModelRecommendedMark => Get(nameof(ModelRecommendedMark));

    /// <summary>'{0}' 모델을 삭제할까요? 다운로드한 파일이 모두 지워집니다.</summary>
    public static string ModelDeleteConfirmFormat => Get(nameof(ModelDeleteConfirmFormat));

    /// <summary>'{0}' 모델을 삭제했습니다.</summary>
    public static string ModelDeletedFormat => Get(nameof(ModelDeletedFormat));

    /// <summary>'{0}' 모델을 삭제하지 못했습니다. ({1})</summary>
    public static string ModelDeleteFailedFormat => Get(nameof(ModelDeleteFailedFormat));

    /// <summary>'{0}' 모델을 검증하는 중입니다...</summary>
    public static string ModelVerifyingFormat => Get(nameof(ModelVerifyingFormat));

    /// <summary>'{0}' 모델 검증에 성공했습니다.</summary>
    public static string ModelVerifyOkFormat => Get(nameof(ModelVerifyOkFormat));

    /// <summary>'{0}' 모델 검증에 실패했습니다. 다시 다운로드하세요.</summary>
    public static string ModelVerifyFailedFormat => Get(nameof(ModelVerifyFailedFormat));

    /// <summary>'{0}' 다운로드를 시작합니다.</summary>
    public static string ModelDownloadStartedFormat => Get(nameof(ModelDownloadStartedFormat));

    /// <summary>'{0}' 다운로드를 완료했습니다.</summary>
    public static string ModelDownloadCompletedFormat => Get(nameof(ModelDownloadCompletedFormat));

    /// <summary>'{0}' 다운로드를 일시정지했습니다. 재개하면 이어받습니다.</summary>
    public static string ModelDownloadPausedFormat => Get(nameof(ModelDownloadPausedFormat));

    /// <summary>'{0}' 다운로드에 실패했습니다. ({1})</summary>
    public static string ModelDownloadFailedFormat => Get(nameof(ModelDownloadFailedFormat));

    /// <summary>{0} / {1} · {2}</summary>
    public static string ModelDownloadProgressFormat => Get(nameof(ModelDownloadProgressFormat));

    /// <summary>모델 목록을 불러오지 못했습니다. ({0})</summary>
    public static string ModelsRefreshFailedFormat => Get(nameof(ModelsRefreshFailedFormat));

    /// <summary>모델 {0}개를 확인했습니다.</summary>
    public static string ModelsLoadedFormat => Get(nameof(ModelsLoadedFormat));

    /// <summary>이미 다운로드 중인 모델입니다.</summary>
    public static string ModelAlreadyDownloading => Get(nameof(ModelAlreadyDownloading));

    /// <summary>다운로드 중인 모델이 아닙니다.</summary>
    public static string ModelNotDownloading => Get(nameof(ModelNotDownloading));

    /// <summary>설명</summary>
    public static string ModelDescriptionLabel => Get(nameof(ModelDescriptionLabel));

    /// <summary>로그 보기</summary>
    public static string LogWindowTitle => Get(nameof(LogWindowTitle));

    /// <summary>폴더 열기</summary>
    public static string OpenLogFolderButton => Get(nameof(OpenLogFolderButton));

    /// <summary>2초마다 자동 새로 고침</summary>
    public static string LogAutoRefreshLabel => Get(nameof(LogAutoRefreshLabel));

    /// <summary>로그 파일</summary>
    public static string LogFileLabel => Get(nameof(LogFileLabel));

    /// <summary>표시할 로그 파일이 없습니다.</summary>
    public static string LogEmptyMessage => Get(nameof(LogEmptyMessage));

    /// <summary>로그 파일을 읽지 못했습니다. ({0})</summary>
    public static string LogReadFailedFormat => Get(nameof(LogReadFailedFormat));

    /// <summary>최근 {0}줄만 표시합니다.</summary>
    public static string LogTailHintFormat => Get(nameof(LogTailHintFormat));

    /// <summary>모델 다운로드</summary>
    public static string ModelPrepareTitle => Get(nameof(ModelPrepareTitle));

    /// <summary>작업을 시작하려면 아래 모델이 필요합니다:</summary>
    public static string ModelPrepareHeader => Get(nameof(ModelPrepareHeader));

    /// <summary> • {0}: {1} ({2})</summary>
    public static string ModelPrepareItemFormat => Get(nameof(ModelPrepareItemFormat));

    /// <summary> — 하드웨어 권장</summary>
    public static string ModelPrepareRecommendedSuffix => Get(nameof(ModelPrepareRecommendedSuffix));

    /// <summary>합계 약 {0}를 내려받습니다. 지금 내려받고 시작할까요?</summary>
    public static string ModelPrepareQuestionFormat => Get(nameof(ModelPrepareQuestionFormat));

    /// <summary>모델을 내려받지 않아 시작하지 않았습니다. 모델 관리 화면에서 직접 내려받을 수도 있습니다.</summary>
    public static string ModelPrepareDeclinedMessage => Get(nameof(ModelPrepareDeclinedMessage));

    /// <summary>모델 내려받는 중 ({0}/{1}) {2} — {3:0}%</summary>
    public static string ModelPrepareProgressFormat => Get(nameof(ModelPrepareProgressFormat));

    /// <summary>모델 준비를 마쳤습니다. 작업을 시작합니다.</summary>
    public static string ModelPrepareCompletedMessage => Get(nameof(ModelPrepareCompletedMessage));

    /// <summary>모델 다운로드를 취소하여 작업을 시작하지 않았습니다.</summary>
    public static string ModelPrepareCancelledMessage => Get(nameof(ModelPrepareCancelledMessage));

    /// <summary>'{0}' 다운로드에 실패하여 작업을 시작하지 않았습니다. ({1})</summary>
    public static string ModelPrepareFailedFormat => Get(nameof(ModelPrepareFailedFormat));

    /// <summary>사용할 모델을 정하지 못했습니다. 하드웨어 감지에 실패했을 수 있습니다. 설정 화면에서 모델을 직접 고르세요.</summary>
    public static string ModelPrepareUnresolvedMessage => Get(nameof(ModelPrepareUnresolvedMessage));

    /// <summary>다운로드 취소</summary>
    public static string CancelModelPrepareButton => Get(nameof(CancelModelPrepareButton));

    /// <summary>모델 사용 설정</summary>
    public static string ModelUseAfterDownloadTitle => Get(nameof(ModelUseAfterDownloadTitle));

    /// <summary>'{0}' 다운로드를 완료했습니다. {1}을(를) 지금부터 이 모델로 설정할까요? 현재 설정: {2}</summary>
    public static string ModelUseAfterDownloadQuestionFormat => Get(nameof(ModelUseAfterDownloadQuestionFormat));

    /// <summary>{0}을(를) '{1}'(으)로 설정했습니다.</summary>
    public static string ModelUseAfterDownloadAppliedFormat => Get(nameof(ModelUseAfterDownloadAppliedFormat));

    /// <summary>번역 엔진도 '{0}'(으)로 함께 바뀝니다. (현재: {1})</summary>
    public static string ModelUseAfterDownloadEngineNote => Get(nameof(ModelUseAfterDownloadEngineNote));

    /// <summary>{0}을(를) '{1}'(으)로, 번역 엔진을 '{2}'(으)로 설정했습니다.</summary>
    public static string ModelUseAfterDownloadAppliedWithEngineFormat => Get(nameof(ModelUseAfterDownloadAppliedWithEngineFormat));

    /// <summary>설정을 저장하지 못했습니다. 설정 화면에서 직접 선택하세요. ({0})</summary>
    public static string ModelUseAfterDownloadFailedFormat => Get(nameof(ModelUseAfterDownloadFailedFormat));
}
